"""
Report Generation Service - Simplified Version
"""
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any
from app.utils.logger import log_info, log_error

class ReportGenerator:
    """Generate incident reports"""
    
    def __init__(self, incident_id: int, event_id: str):
        self.incident_id = incident_id
        self.event_id = event_id
        self.reports_dir = Path("/tmp/soc-agent-reports")
        self.reports_dir.mkdir(exist_ok=True)
    
    def generate_markdown(self, analysis: Dict[str, Any], severity: str) -> str:
        """Generate Markdown report"""
        try:
            log_info("Generating markdown report", incident_id=self.incident_id)
            
            step1 = analysis.get("step_1_classification", {})
            step2 = analysis.get("step_2_threat_assessment", {})
            step5 = analysis.get("step_5_remediation", {})
            
            lines = [
                "# Security Incident Report",
                "",
                f"**Incident ID:** {self.incident_id}",
                f"**Event ID:** {self.event_id}",
                f"**Severity:** {severity}",
                f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                "",
                "---",
                "",
                "## Classification",
                "",
                f"**Attack Type:** {step1.get('attack_type', 'Unknown')}",
                f"**MITRE Technique:** {step1.get('mitre_technique', 'N/A')}",
                f"**Category:** {step1.get('category', 'Unknown')}",
                "",
                f"**Description:** {step1.get('brief_description', 'No description')}",
                "",
                "---",
                "",
                "## Threat Assessment",
                "",
                f"**Severity:** {step2.get('severity', 'UNKNOWN')}",
                f"**Threat Score:** {step2.get('threat_score', 'N/A')}/10",
                "",
                f"**Reasoning:** {step2.get('reasoning', 'Unknown')}",
                "",
                "---",
                "",
                "## Immediate Actions",
                "",
            ]
            
            for action in step5.get('immediate_actions', []):
                lines.append(f"- **{action.get('action', 'Unknown')}** ({action.get('time', 'Unknown')})")
                lines.append(f"  ```")
                lines.append(f"  {action.get('command', 'No command')}")
                lines.append(f"  ```")
                lines.append("")
            
            lines.append("---")
            lines.append("")
            lines.append("*This report was auto-generated by SOC Agent AI*")
            
            return "\n".join(lines)
            
        except Exception as e:
            log_error("Markdown generation failed", error=str(e))
            raise
    
    def save_markdown(self, markdown_content: str) -> str:
        """Save markdown report"""
        try:
            filepath = self.reports_dir / f"incident_{self.incident_id}_{self.event_id}.md"
            filepath.write_text(markdown_content)
            log_info("Markdown saved", filepath=str(filepath))
            return str(filepath)
        except Exception as e:
            log_error("Failed to save markdown", error=str(e))
            raise
    
    def generate_pdf(self, analysis: Dict[str, Any], severity: str) -> str:
        """Generate simple PDF report"""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            
            log_info("Generating PDF report", incident_id=self.incident_id)
            
            filepath = self.reports_dir / f"incident_{self.incident_id}_{self.event_id}.pdf"
            doc = SimpleDocTemplate(str(filepath), pagesize=letter)
            elements = []
            styles = getSampleStyleSheet()
            
            step1 = analysis.get("step_1_classification", {})
            step2 = analysis.get("step_2_threat_assessment", {})
            
            elements.append(Paragraph("Security Incident Report", styles['Title']))
            elements.append(Spacer(1, 0.3*inch))
            
            elements.append(Paragraph(f"Incident ID: {self.incident_id}", styles['Normal']))
            elements.append(Paragraph(f"Severity: {severity}", styles['Normal']))
            elements.append(Paragraph(f"Attack Type: {step1.get('attack_type', 'Unknown')}", styles['Normal']))
            elements.append(Paragraph(f"Threat Score: {step2.get('threat_score', 'N/A')}/10", styles['Normal']))
            
            doc.build(elements)
            log_info("PDF saved", filepath=str(filepath))
            return str(filepath)
            
        except Exception as e:
            log_error("PDF generation failed", error=str(e))
            raise
    
    def generate_all(self, analysis: Dict[str, Any], severity: str) -> Dict[str, str]:
        """Generate all reports"""
        try:
            md_content = self.generate_markdown(analysis, severity)
            md_path = self.save_markdown(md_content)
            pdf_path = self.generate_pdf(analysis, severity)
            return {"markdown": md_path, "pdf": pdf_path}
        except Exception as e:
            log_error("Report generation failed", error=str(e))
            raise
